# Generated by Django 4.0.2 on 2022-03-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('ime_roditelja', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('jmbg', models.BigIntegerField()),
                ('datum_rodjenja', models.DateField()),
                ('broj_telefona', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('broj_indeksa', models.CharField(max_length=10)),
                ('godina_studija', models.CharField(max_length=10)),
                ('slika', models.ImageField(upload_to='pics')),
                ('espb', models.FloatField(default=0.0, null=True)),
                ('prosek_ocena', models.FloatField(default=0.0, null=True)),
            ],
        ),
    ]
