# Generated by Django 4.0.2 on 2022-03-17 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studenti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Predmeti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100)),
                ('godina_studija', models.CharField(max_length=10)),
                ('sifra', models.CharField(max_length=100)),
                ('espb', models.FloatField(null=True)),
                ('obavezni_izborni', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ocene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ocena', models.IntegerField()),
                ('datum', models.DateField()),
                ('predmet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predmeti.predmeti')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studenti.studenti')),
            ],
        ),
    ]
